INSERT INTO users(bondholder,email,password,	   type) VALUES  ('AZ Holdings Inc', 	'az@ak.de'	,'password'	 , 'CORP')    ;
INSERT INTO users(bondholder,email,password,	   type) VALUES   ('Acme co', 	'ac@ak.de'	,'password'	 , 'CORP')    ;
INSERT INTO users(bondholder,email,password,	   type) VALUES   ('Sovereign Investments',   	'si@ak.de'	,'password'	 , 'CORP')    ;
INSERT INTO users(bondholder,email,password,	   type) VALUES   ('Astra Trading Ltd',   	'at@ak.de'	,'password',	  'CORP')    ;
INSERT INTO users(bondholder,email,password,	   type) VALUES   ('Muncipal Gov Of Orange County',   	'mg@ak.de'	,'password'	  ,'CORP')    ;
INSERT INTO users(bondholder,email,password,	   type) VALUES   ('Goldman Sachs',   	'gs@ak.de'	,'password'	,  'GOVN')    ;
INSERT INTO users(bondholder,email,password,	   type) VALUES   ('UBS' ,	'ubs@ak.de'	,'password'	 , 'GOVN')    ;
INSERT INTO users(bondholder,email,password,	   type) VALUES   ('Barclays'  ,  	'bc@ak.de'	,'password'	 , 'GOVN')    ;
INSERT INTO users(bondholder,email,password,	   type) VALUES   ('British Telecom' ,	'bt@ak.de',	'password'	 , 'GOVN')    ;
INSERT INTO users(bondholder,email,password,	   type) VALUES   ('Pension Holdings'   , 	'@ak.de'	,'password'	,  'CORP')    ;
INSERT INTO users(bondholder,email,password,	   type) VALUES   ('Zurich Pension fund 4' ,  	'az@ak.de'	,'password'	,  'SOVN')    ;


INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('trading_book_1','active','05-08-21','BNPParibasIssu 4,37% Microsoft Corp (USD)','XS1988387210',1000,NULL,'USD',4.37,90);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('trading_book_1','active','05-08-21','BNPParibasIssu 4,37% Microsoft Corp (USD)','XS1988387210',1000,NULL,'USD',4.37,89.56);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('trading_book_2','active','30-07-21','Airbus 3.15%  USD','USN0280EAR64',900,'123456780','USD',3.15,105.775);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_3','active','30-09-21','UBS Facebook (USD)','A12356111',900,'123456bh0','USD',2,90);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_2','active','30-09-21','UBS Facebook (USD)','A12356111',900,'123456bh0','USD',2,90);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_4','active','03-08-21','Amazon','USU02320AG12',900,'AMZN 3.15 08/22/27 REGS','USD',3.15,98.56);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460505',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460506',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460507',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460508',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460509',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460510',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460511',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460512',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460513',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460515',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460514',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_4','active','06-08-21','TEMASEK FINL I LTD GLOBAL MEDIUM TERM NTS BOOK ENTRY REG S','US87973RAA86',690,'87973RAA8','USD',2.02,100.13);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_4','active','22-12-30','First Norway Alpha Kl.IV','IE00B29LNP31',340,'87973RAA8','USD',1.123,98.76);

INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES          ('buy'    ,  '1'   ,  'XS1988387210' ,  'USD'  ,  '13-05-21' ,  'open' ,  '04-08-21' ,  50)    ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  '2'   ,  'XS1988387210' ,  'GBP'  ,  '04-02-21' ,  'open' ,  '04-08-21' ,  40)    ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '3'   ,  'USN0280EAR64' ,  'USD'  ,  '13-05-21' ,  'open' ,  '23-08-21' ,  1000)  ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  '3'   ,  'USN0280EAR64' ,  'GBP'  ,  '04-02-21' ,  'open' ,  '10-09-21' ,  900)   ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '4'   ,  'A12356111'    ,  'USD'  ,  '13-05-21' ,  'open' ,  '23-08-21' ,  50)    ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy', '3', 'USN0280EAR64', 'USD', '13-05-21', 'open', '23-08-21', 1000);
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  '4'   ,  'A12356111'    ,  'USD'  ,  '13-05-21' ,  'open' ,  '23-08-21' ,  50)    ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '5'   ,  'USU02320AG12' ,  'GBP'  ,  '04-02-21' ,  'open' ,  '27-09-21' ,  60)    ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '6'   ,  'USU02320AG12' ,  'USD'  ,  '23-08-21' ,  'open' ,  '23-08-21' ,  50)    ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '7'   ,  'GB00B6460505' ,  'GBP'  ,  '27-09-21' ,  'open' ,  '27-09-21' ,  1100)  ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  '8'   ,  'GB00B6460506' ,  'GBP'  ,  '28-09-21' ,  'open' ,  '28-09-21' ,  900)   ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '9'   ,  'GB00B6460507' ,  'GBP'  ,  '29-09-21' ,  'open' ,  '29-09-21' ,  2000)  ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  '10'   ,  'GB00B6460508' ,  'GBP'  ,  '30-09-21' ,  'open' ,  '30-09-21' ,  2000)  ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '11'   ,  'GB00B6460509' ,  'GBP'  ,  '01-10-21' ,  'open' ,  '01-10-21' ,  1000)  ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '12'   ,  'GB00B6460510' ,  'GBP'  ,  '02-10-19' ,  'open' ,  '02-10-19' ,  900)   ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  '13'   ,  'GB00B6460511' ,  'GBP'  ,  '03-10-19' ,  'open' ,  '03-10-19' ,  1900)  ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '14'   ,  'GB00B6460512' ,  'GBP'  ,  '04-10-18' ,  'open' ,  '04-10-18' ,  600)   ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '15'   ,  'GB00B6460513' ,  'GBP'  ,  '05-10-19' ,  'open' ,  '05-10-19' ,  600)   ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '16'   ,  'GB00B6460514' ,  'GBP'  ,  '06-06-21' ,  'open' ,  '06-06-21' ,  700)   ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  '17'   ,  'GB00B6460515' ,  'GBP'  ,  '07-10-11' ,  'open' ,  '07-10-21' ,  1300)  ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '18'   ,  'US87973RAA86' ,  'USD'  ,  '04-02-12' ,  'open' ,  '27-09-21' ,  60)    ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '18'   ,  'US87973RAA86' ,  'USD'  ,  '23-08-12' ,  'open' ,  '23-08-21' ,  50)    ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '18'   ,  'US87973RAA86' ,  'USD'  ,  '04-02-13' ,  'open' ,  '27-09-21' ,  75)    ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '18'   ,  'US87973RAA86' ,  'USD'  ,  '23-08-14' ,  'open' ,  '23-08-21' ,  50)    ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '19'   ,  'IE00B29LNP31' ,  'USD'  ,  '04-02-16' ,  'open' ,  '27-09-21' ,  300)   ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '19'   ,  'IE00B29LNP31' ,  'USD'  ,  '23-08-12' ,  'open' ,  '23-08-21' ,  300)   ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  '19'   ,  'IE00B29LNP31' ,  'USD'  ,  '04-02-13' ,  'open' ,  '27-09-21' ,  300)   ;
INSERT INTO trades(tradetype,   bookid,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  '19'   ,  'IE00B29LNP31' ,  'USD'  ,  '23-08-15' ,  'open' ,  '23-08-21' ,  300);

INSERT INTO booksusers(userid,bookid) VALUES		(1,1)	;
INSERT INTO booksusers(userid,bookid) VALUES		(1,2)	;
INSERT INTO booksusers(userid,bookid) VALUES		(2,3)	;
INSERT INTO booksusers(userid,bookid) VALUES		(2,3)	;
INSERT INTO booksusers(userid,bookid) VALUES		(3,4)	;
INSERT INTO booksusers(userid,bookid) VALUES		(4,3)	;
INSERT INTO booksusers(userid,bookid) VALUES		(3,5)	;
INSERT INTO booksusers(userid,bookid) VALUES		(5,6)	;
INSERT INTO booksusers(userid,bookid) VALUES		(5,6)	;
INSERT INTO booksusers(userid,bookid) VALUES		(6,7)	;
INSERT INTO booksusers(userid,bookid) VALUES		(6,8)	;
INSERT INTO booksusers(userid,bookid) VALUES		(7,9)	;
INSERT INTO booksusers(userid,bookid) VALUES		(7,10)	;
INSERT INTO booksusers(userid,bookid) VALUES		(8,11)	;
INSERT INTO booksusers(userid,bookid) VALUES		(8,12)	;
INSERT INTO booksusers(userid,bookid) VALUES		(8,13)	;
INSERT INTO booksusers(userid,bookid) VALUES		(9,14)	;
INSERT INTO booksusers(userid,bookid) VALUES		(10,15)	;
INSERT INTO booksusers(userid,bookid) VALUES		(10,16)	;
INSERT INTO booksusers(userid,bookid) VALUES		(10,17)	;
INSERT INTO booksusers(userid,bookid) VALUES		(11,18)	;
INSERT INTO booksusers(userid,bookid) VALUES		(11,18)	;
INSERT INTO booksusers(userid,bookid) VALUES		(11,18)	;
INSERT INTO booksusers(userid,bookid) VALUES		(11,18)	;
INSERT INTO booksusers(userid,bookid) VALUES		(11,19)	;
INSERT INTO booksusers(userid,bookid) VALUES		(11,19)	;
INSERT INTO booksusers(userid,bookid) VALUES		(11,19)	;
INSERT INTO booksusers(userid,bookid) VALUES		(11,19)	;