INSERT INTO users(bondholder,	type) VALUES	('AZ Holdings Inc'	,	'CORP')	;
INSERT INTO users(bondholder,	type) VALUES	('Acme co'	,	'CORP')	;
INSERT INTO users(bondholder,	type) VALUES	('Sovereign Investments'	,	'CORP')	;
INSERT INTO users(bondholder,	type) VALUES	('Astra Trading Ltd'	,	'CORP')	;
INSERT INTO users(bondholder,	type) VALUES	('Sovereign Investments'	,	'CORP')	;
INSERT INTO users(bondholder,	type) VALUES	('Muncipal Gov Of Orange County'	,	'CORP')	;
INSERT INTO users(bondholder,	type) VALUES	('Goldman Sachs'	,	'GOVN')	;
INSERT INTO users(bondholder,	type) VALUES	('UBS'	,	'GOVN')	;
INSERT INTO users(bondholder,	type) VALUES	('Barclays'	,	'GOVN')	;
INSERT INTO users(bondholder,	type) VALUES	('British Telecom'	,	'GOVN')	;
INSERT INTO users(bondholder,	type) VALUES	('Zurich Pension fund 4'	,	'SOVN')	;


INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('trading_book_1','active','05-08-21','BNPParibasIssu 4,37% Microsoft Corp (USD)','XS1988387210',1000,NULL,'USD',4.37,90);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('trading_book_2','active','30-07-21','Airbus 3.15%  USD','USN0280EAR64',900,'123456780','USD',3.15,105.775);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_3','active','30-09-21','UBS Facebook (USD)','A12356111',900,'123456bh0','USD',2,90);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_2','active','30-09-21','UBS Facebook (USD)','A12356111',900,'123456bh0','USD',2,90);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_4','active','03-08-21','Amazon','USU02320AG12',900,'AMZN 3.15 08/22/27 REGS','USD',3.15,98.56);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460505',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460506',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460507',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460508',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460509',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460510',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460511',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460512',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460513',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460515',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_6','active','09-08-21','HM Treasury United Kingdon','GB00B6460514',900,'BDCHBW8','GBP',0.75,110.35);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_4','active','06-08-21','TEMASEK FINL I LTD GLOBAL MEDIUM TERM NTS BOOK ENTRY REG S','US87973RAA86',690,'87973RAA8','USD',2.02,100.13);
INSERT INTO books(bookname,status,bondmaturitydate,issuername,isin,facevalue,cusip,bondcurrency,couponpercent,unitprice) VALUES ('Trading_book_4','active','22-12-30','First Norway Alpha Kl.IV','IE00B29LNP31',340,'87973RAA8','USD',1.123,98.76);

INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES          ('buy'    ,  'trading_book_1'   ,  'XS1988387210' ,  'USD'  ,  '13-05-21' ,  'open' ,  '04-08-21' ,  50)    ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  'trading_book_1'   ,  'XS1988387210' ,  'GBP'  ,  '04-02-21' ,  'open' ,  '04-08-21' ,  40)    ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'trading_book_2'   ,  'USN0280EAR64' ,  'USD'  ,  '13-05-21' ,  'open' ,  '23-08-21' ,  1000)  ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  'trading_book_2'   ,  'USN0280EAR64' ,  'GBP'  ,  '04-02-21' ,  'open' ,  '10-09-21' ,  900)   ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_3'   ,  'A12356111'    ,  'USD'  ,  '13-05-21' ,  'open' ,  '23-08-21' ,  50)    ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  'Trading_book_2'   ,  'A12356111'    ,  'USD'  ,  '13-05-21' ,  'open' ,  '23-08-21' ,  50)    ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_4'   ,  'USU02320AG12' ,  'GBP'  ,  '04-02-21' ,  'open' ,  '27-09-21' ,  60)    ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_4'   ,  'USU02320AG12' ,  'USD'  ,  '23-08-21' ,  'open' ,  '23-08-21' ,  50)    ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_6'   ,  'GB00B6460505' ,  'GBP'  ,  '27-09-21' ,  'open' ,  '27-09-21' ,  1100)  ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  'Trading_book_6'   ,  'GB00B6460506' ,  'GBP'  ,  '28-09-21' ,  'open' ,  '28-09-21' ,  900)   ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_6'   ,  'GB00B6460507' ,  'GBP'  ,  '29-09-21' ,  'open' ,  '29-09-21' ,  2000)  ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  'Trading_book_6'   ,  'GB00B6460508' ,  'GBP'  ,  '30-09-21' ,  'open' ,  '30-09-21' ,  2000)  ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_6'   ,  'GB00B6460509' ,  'GBP'  ,  '01-10-21' ,  'open' ,  '01-10-21' ,  1000)  ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_6'   ,  'GB00B6460510' ,  'GBP'  ,  '02-10-19' ,  'open' ,  '02-10-19' ,  900)   ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  'Trading_book_6'   ,  'GB00B6460511' ,  'GBP'  ,  '03-10-19' ,  'open' ,  '03-10-19' ,  1900)  ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_6'   ,  'GB00B6460512' ,  'GBP'  ,  '04-10-18' ,  'open' ,  '04-10-18' ,  600)   ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_6'   ,  'GB00B6460513' ,  'GBP'  ,  '05-10-19' ,  'open' ,  '05-10-19' ,  600)   ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_6'   ,  'GB00B6460514' ,  'GBP'  ,  '06-06-21' ,  'open' ,  '06-06-21' ,  700)   ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  'Trading_book_6'   ,  'GB00B6460515' ,  'GBP'  ,  '07-10-11' ,  'open' ,  '07-10-21' ,  1300)  ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_4'   ,  'US87973RAA86' ,  'USD'  ,  '04-02-12' ,  'open' ,  '27-09-21' ,  60)    ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_4'   ,  'US87973RAA86' ,  'USD'  ,  '23-08-12' ,  'open' ,  '23-08-21' ,  50)    ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_4'   ,  'US87973RAA86' ,  'USD'  ,  '04-02-13' ,  'open' ,  '27-09-21' ,  75)    ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_4'   ,  'US87973RAA86' ,  'USD'  ,  '23-08-14' ,  'open' ,  '23-08-21' ,  50)    ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_4'   ,  'IE00B29LNP31' ,  'USD'  ,  '04-02-16' ,  'open' ,  '27-09-21' ,  300)   ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_4'   ,  'IE00B29LNP31' ,  'USD'  ,  '23-08-12' ,  'open' ,  '23-08-21' ,  300)   ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('buy' ,  'Trading_book_4'   ,  'IE00B29LNP31' ,  'USD'  ,  '04-02-13' ,  'open' ,  '27-09-21' ,  300)   ;
INSERT INTO trades(tradetype,   bookname,  isin,  tradecurrency, tradedate, tradestatus,   tradesettlementdate,   quantity) VALUES         ('sell'    ,  'Trading_book_4'   ,  'IE00B29LNP31' ,  'USD'  ,  '23-08-15' ,  'open' ,  '23-08-21' ,  300);

INSERT INTO booksUsers(bondholder,  bookname) VALUES   ('AZ Holdings Inc'    ,  'trading_book_1')  ;
INSERT INTO booksUsers(bondholder,  bookname) VALUES   ('Acme co' ,  'trading_book_2')  ;
INSERT INTO booksUsers(bondholder,  bookname) VALUES   ('Sovereign Investments'   ,  'Trading_book_3')  ;
INSERT INTO booksUsers(bondholder,  bookname) VALUES   ('Astra Trading Ltd'   ,  'trading_book_2')  ;
INSERT INTO booksUsers(bondholder,  bookname) VALUES   ('Sovereign Investments'   ,  'Trading_book_2')  ;
INSERT INTO booksUsers(bondholder,  bookname) VALUES   ('Muncipal Gov Of Orange County'   ,  'Trading_book_4')  ;
INSERT INTO booksUsers(bondholder,  bookname) VALUES   ('Goldman Sachs'   ,  'Trading_book_6')  ;
INSERT INTO booksUsers(bondholder,  bookname) VALUES   ('UBS' ,  'Trading_book_6')  ;
INSERT INTO booksUsers(bondholder,  bookname) VALUES   ('Barclays'    ,  'Trading_book_6')  ;
INSERT INTO booksUsers(bondholder,  bookname) VALUES   ('British Telecom' ,  'Trading_book_6')  ;
INSERT INTO booksUsers(bondholder,  bookname) VALUES   ('Pension Holdings'          ,  'Trading_book_6')  ;
INSERT INTO booksUsers(bondholder,  bookname) VALUES   ('Zurich Pension fund 4'   ,  'Trading_book_4')  ;
